version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: effective_db
      TZ: 'Europe/Moscow'
    volumes:
      - ./migrations/001_create_users_table.sql:/docker-entrypoint-initdb.d/001_create_users_table.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d effective_db']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: effective_db

      AGIFY_API_URL: 'https://api.agify.io/'
      GENDERIZE_API_URL: 'https://api.genderize.io/'
      NATIONALIZE_API_URL: 'https://api.nationalize.io/'
      PORT: '3000'
      TZ: 'Europe/Moscow'
    ports:
      - '3000:3000'

volumes:
  pgdata:
